<?php

namespace BioWare\Interview\MessengerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendListRepository extends EntityRepository
{
}
